name: MLOPS-DEPLOY

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t mlops1-house-price-api:latest .

      - name: Tag Docker image
        run: docker tag mlops1-house-price-api:latest ${{ secrets.DOCKER_HUB_USERNAME }}/mlops1-house-price-api:latest

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin

      - name: Push to Docker Hub with retry
        run: |
          retry() {
            n=0
            until [ "$n" -ge 5 ]; do
              docker push ${{ secrets.DOCKER_HUB_USERNAME }}/mlops1-house-price-api:latest && break
              n=$((n+1))
              echo "Retrying push in 5 seconds..."
              sleep 5
            done
          }
          retry

      - name: Install sshpass
        run: sudo apt-get install sshpass

      - name: Connect to SSH and Deploy
        run: |
          sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} << 'EOF'
            if [ ! -d "/home/ubuntu/abel.andry" ]; then
              mkdir /home/ubuntu/abel.andry
            fi
            cd /home/ubuntu/abel.andry
            docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/mlops1-house-price-api:latest
            docker stop mlops1-house-price-api || true
            docker rm mlops1-house-price-api || true  # Ensure container is removed before re-running
            docker run -d -p 8025:8025 --name mlops1-house-price-api ${{ secrets.DOCKER_HUB_USERNAME }}/mlops1-house-price-api:latest
          EOF

      - name: Test the deployment
        run: |
          curl -X POST http://${{ secrets.SSH_HOST }}:8025/predict \
          -H "Content-Type: application/json" \
          -d '{"size": 120, "nb_rooms":3, "garden": 1}'